### ISSUE TITLE
BUG: Webpage after logging in loads to a blank screen the first time, loads fine after refreshing

### ISSUE THREAD

**Issue by francisli** [peakresponse/peak-server#88]
![Screen Shot 2021-04-06 at 3 50 37 PM](https://user-images.githubusercontent.com/42448914/113787716-6114c280-96f0-11eb-955d-2e263ac8f49a.png)

**Comment by francisli** [comment]
@brittmj which browser were you using?

**Comment by brittmj** [comment]
Sorry, that's an important detail.  Google Chrome
